---
name: Rollout to DigitalOcean

#
# Trigger a rollout restart of all given deployments.
#

on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      cluster-name:
        description: Target cluster name
        required: true
        type: string
      config-path:
        description: Path to configuration folder
        required: true
        type: string
    secrets:
      DIGITALOCEAN_API_TOKEN:
        description: DigitalOcean API token
        required: true

jobs:
  rollout:
    name: Rollout kubernetes config ${{ inputs.config-path }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install doctl tool
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_API_TOKEN }}
      - name: Save DigitalOcean kubeconfig
        run: doctl k8s cluster kubeconfig save ${{ inputs.cluster-name }}
      - name: Apply config
        run: kubectl apply -k ${{ inputs.config-path }}
