---
name: Lint

on:  # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main
  push:
    branches:
      - main

jobs:
  yaml-lint:
    name: Lint YAML & Dockerfile
    uses: ./.github/workflows/lint-yaml-and-docker.yml
    with:
      enable-docker-linting: false
