---
name: Lint Infrastructure

#
# Validate all configuration files
#

on:
  workflow_call:

jobs:
  yaml-lint:
    name: Lint YAML
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        uses: wisemen-digital/devops-ga-lint-yaml@main

  env-lint:
    name: Lint Environment Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lint
        run: |
          shopt -s globstar
          result=0

          for file in **/env/*.properties; do
            echo "Found ${file}"
            if [[ "$file" == *"/base/"* ]]; then continue; fi

            # Try to find base env
            filename=$(basename $file)
            base="$(dirname $file)/../../../base/env/$filename"
            if [ ! -f "$base" ]; then
              echo "::warning file=$file::Base file not found ($base)."
              continue
            fi

            # Diff keys
            echo "Comparing $file to $(realpath --relative-to "." $base)…"
            keys_diff=`diff \
              <(yq -o=props -p=props 'keys | sort | .[]' $base) \
              <(yq -o=props -p=props 'keys | sort | .[]' $file)`
            if [[ -z "$keys_diff" ]]; then continue; fi

            # Generate errors
            echo $keys_diff | while read -r line; do
              if [[ $line == "> "* ]]; then
                echo "::error file=$file::Extraneous key ${line:2}, remove it (or add it to base)."
                result=1
              elif [[ $line == "< "* ]]; then
                echo "::error file=$file::Missing key ${line:2}, add it."
                result=1
              fi
            done
          done
          exit $result
