---
name: Rollout object storage (Scaleway)

#
# Check what's changed (via filters, or provide your own list) and roll it out.
#

on:
  workflow_call:
    # Depends on the following vars
    # - SCALEWAY_REGION
    inputs:
      # bucket info
      bucket-deployments:
        description: List of deployments to roll out (folders), separated by commas
        required: false
        type: string
    secrets:
      SCALEWAY_ACCESS_KEY:
        description: Scaleway API key ID
        required: true
      SCALEWAY_SECRET_KEY:
        description: Scaleway API key secret
        required: true

jobs:
  generate-matrix:
    name: Generate job matrices
    runs-on: ubuntu-latest
    outputs:
      deployments: ${{ steps.changed-paths-filter.outputs.matrix }}
    steps:
      - name: Generate Matrix
        id: changed-paths-filter
        uses: wisemen-digital/devops-ga-changed-paths-filter@main
        with:
          filter-file: .github/s3-rollout-filters.yaml
          changes-override: ${{ inputs.bucket-deployments }}

  rollout-to-s3:
    name: Rollout to s3
    needs: [generate-matrix]
    strategy:
      matrix:
        deployment: ${{ fromJson(needs.generate-matrix.outputs.deployments) }}
    if: ${{ needs.generate-matrix.outputs.deployments != '[]' }}
    runs-on: ubuntu-latest
    environment: ${{ matrix.deployment.environment }}
    steps:
      - name: Apply Configuration
        uses: wisemen-digital/devops-ga-s3-apply@main
        with:
          provider: scaleway
          region: ${{ vars.SCALEWAY_REGION }}
          config-path: ${{ matrix.deployment.path }}
          access-key: ${{ secrets.SCALEWAY_ACCESS_KEY }}
          secret-key: ${{ secrets.SCALEWAY_SECRET_KEY }}
