---
name: Promote to environment (Scaleway)

#
# Calculate previous environment, re-tag the image and roll it out.
#

on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      environment-source:
        description: Source environment to deploy FROM (defaults to previous environment)
        type: string
        required: false
      environment-target:
        description: Target environment to deploy TO
        type: string
        required: true
      # Scaleway information
      scaleway-container-registry:
        description: Container registry endpoint
        required: true
        type: string
      scaleway-organization-id:
        description: Scaleway organization ID
        required: true
        type: string
      scaleway-project-id:
        description: Scaleway project ID
        required: true
        type: string
      scaleway-region:
        description: Target deployment region (such as nl-ams)
        required: true
        type: string
      scaleway-cluster-id:
        description: Target cluster ID
        required: true
        type: string
      # Cluster info
      cluster-deployments:
        description: List of deployments to rollout
        required: false
        type: string
      cluster-labels:
        description: List of labels to rollout
        required: false
        type: string
      # Extra options, probably not needed
      environment-map:
        description: Environment map (JSON, fallback to default map)
        type: string
        required: false
    secrets:
      SCALEWAY_ACCESS_KEY:
        description: Scaleway API key ID
        required: true
      SCALEWAY_SECRET_KEY:
        description: Scaleway API key secret
        required: true

jobs:
  fetch-namespace:
    uses: ./.github/workflows/github-fetch-environment-variable.yml
    with:
      environment: ${{ inputs.environment-target }}
      variable: K8S_NAMESPACE

  calculate-source:
    uses: ./.github/workflows/github-calculate-source-environment.yml
    with:
      target: ${{ inputs.environment-target }}
      source: ${{ inputs.environment-source }}

  docker-add-tag:
    needs: calculate-source
    uses: ./.github/workflows/docker-add-tag.yml
    with:
      container-registry: ${{ inputs.scaleway-container-registry }}
      source-tag: ${{ needs.calculate-source.outputs.source }}
      target-tag: ${{ needs.calculate-source.outputs.target }}
    secrets:
      CONTAINER_REGISTRY_USERNAME: nologin
      CONTAINER_REGISTRY_PASSWORD: ${{ secrets.SCALEWAY_SECRET_KEY }}

  rollout:
    name: Rollout to k8s
    needs: [fetch-namespace, docker-add-tag]
    runs-on: ubuntu-latest
    steps:
      - name: Rollout on cluster
        uses: wisemen-digital/devops-ga-k8s-rollout@main
        with:
          vendor: scaleway
          cluster-id: ${{ inputs.scaleway-cluster-id }}
          rollout-deployments: ${{ inputs.cluster-deployments }}
          rollout-labels: ${{ inputs.cluster-labels }}
          rollout-namespace: ${{ needs.fetch-namespace.outputs.value }}
          scaleway-organization-id: ${{ inputs.scaleway-organization-id }}
          scaleway-project-id: ${{ inputs.scaleway-project-id }}
          scaleway-region: ${{ inputs.scaleway-region }}
          scaleway-access-key: ${{ secrets.SCALEWAY_ACCESS_KEY }}
          scaleway-secret-key: ${{ secrets.SCALEWAY_SECRET_KEY }}
