---
name: Build & deploy to environment (DigitalOcean)

#
# Build the docker image, and deploy it to the given environment.
#

on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      environment:
        description: Target environment to deploy to
        type: string
        required: true
      # DigitalOcean information
      digitalocean-container-registry:
        description: Container registry endpoint
        required: true
        type: string
      digitalocean-cluster-id:
        description: Target cluster ID
        required: true
        type: string
      # Cluster info
      cluster-deployments:
        description: List of deployments to rollout
        required: false
        type: string
      cluster-labels:
        description: List of labels to rollout
        required: false
        type: string
    secrets:
      DIGITALOCEAN_API_USER:
        description: DigitalOcean user email
        required: true
      DIGITALOCEAN_API_TOKEN:
        description: DigitalOcean API token
        required: true

jobs:
  build-and-deploy:
    name: Build & Deploy to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Docker build & push
        uses: wisemen-digital/devops-ga-docker-build-push@main
        with:
          container-registry: ${{ inputs.scaleway-container-registry }}
          container-registry-username: ${{ secrets.DIGITALOCEAN_API_USER }}
          container-registry-password: ${{ secrets.DIGITALOCEAN_API_TOKEN }}
          github-access-token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ inputs.environment }}
      - name: Rollout on cluster
        uses: wisemen-digital/devops-ga-k8s-rollout@main
        with:
          vendor: digitalocean
          cluster-id: ${{ inputs.digitalocean-cluster-id }}
          rollout-deployments: ${{ inputs.cluster-deployments }}
          rollout-labels: ${{ inputs.cluster-labels }}
          rollout-namespace: ${{ needs.fetch-namespace.outputs.value }}
          digitalocean-api-token: ${{ secrets.DIGITALOCEAN_API_TOKEN }}
