---
name: Build & deploy to environment (Scaleway)

#
# Build the docker image, and deploy it to the given environment.
#

on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      environment:
        description: Target environment to deploy to
        type: string
        required: true
      # Scaleway information
      scaleway-container-registry:
        description: Container registry endpoint
        required: true
        type: string
      scaleway-organization-id:
        description: Scaleway organization ID
        required: true
        type: string
      scaleway-project-id:
        description: Scaleway project ID
        required: true
        type: string
      scaleway-region:
        description: Target deployment region (such as nl-ams)
        required: true
        type: string
      scaleway-cluster-id:
        description: Target cluster ID
        required: true
        type: string
      # Cluster info
      cluster-deployments:
        description: List of deployments to rollout
        required: false
        type: string
      cluster-labels:
        description: List of labels to rollout
        required: false
        type: string
    secrets:
      SCALEWAY_ACCESS_KEY:
        description: Scaleway API key ID
        required: true
      SCALEWAY_SECRET_KEY:
        description: Scaleway API key secret
        required: true

jobs:
  build-and-deploy:
    name: Build & Deploy to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Docker build & push
        uses: wisemen-digital/devops-ga-docker-build-push@main
        with:
          container-registry: ${{ inputs.scaleway-container-registry }}
          container-registry-username: nologin
          container-registry-password: ${{ secrets.SCALEWAY_SECRET_KEY }}
          github-access-token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ inputs.environment }}
      - name: Rollout on cluster
        uses: wisemen-digital/devops-ga-k8s-rollout@main
        with:
          vendor: scaleway
          cluster-id: ${{ inputs.scaleway-cluster-id }}
          rollout-deployments: ${{ inputs.cluster-deployments }}
          rollout-labels: ${{ inputs.cluster-labels }}
          rollout-namespace: ${{ needs.fetch-namespace.outputs.value }}
          scaleway-organization-id: ${{ inputs.scaleway-organization-id }}
          scaleway-project-id: ${{ inputs.scaleway-project-id }}
          scaleway-region: ${{ inputs.scaleway-region }}
          scaleway-access-key: ${{ secrets.SCALEWAY_ACCESS_KEY }}
          scaleway-secret-key: ${{ secrets.SCALEWAY_SECRET_KEY }}
