---
name: Promote to environment (Scaleway)

#
# Calculate previous environment, re-tag the image and roll it out.
#

on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      environment-source:
        description: Source environment to deploy FROM (defaults to previous environment)
        type: string
        required: false
      environment-target:
        description: Target environment to deploy TO
        type: string
        required: true
      # Scaleway information
      scaleway-container-registry:
        description: Container registry endpoint
        required: true
        type: string
      scaleway-organization-id:
        description: Scaleway organization ID
        required: true
        type: string
      scaleway-project-id:
        description: Scaleway project ID
        required: true
        type: string
      scaleway-region:
        description: Target deployment region (such as nl-ams)
        required: true
        type: string
      scaleway-cluster-id:
        description: Target cluster ID
        required: true
        type: string
      # Cluster info
      cluster-deployments:
        description: List of deployments to rollout
        required: false
        type: string
      cluster-labels:
        description: List of labels to rollout
        required: false
        type: string
      # Extra options, probably not needed
      environment-map:
        description: Environment map (JSON, fallback to default map)
        type: string
        required: false
    secrets:
      SCALEWAY_ACCESS_KEY:
        description: Scaleway API key ID
        required: true
      SCALEWAY_SECRET_KEY:
        description: Scaleway API key secret
        required: true

jobs:
  promote-tag:
    name: Promote to ${{ inputs.environment-target }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment-target }}
    steps:
      - name: Re-tag image
        uses: wisemen-digital/devops-ga-docker-promote-tag@main
        with:
          container-registry: ${{ inputs.scaleway-container-registry }}
          container-registry-username: nologin
          container-registry-password: ${{ secrets.SCALEWAY_SECRET_KEY }}
          source-tag: ${{ inputs.environment-source }}
          target-tag: ${{ inputs.environment-target }}
          tag-map: ${{ inputs.environment-map }}
      - name: Rollout on cluster
        uses: wisemen-digital/devops-ga-k8s-rollout@main
        with:
          vendor: scaleway
          cluster-id: ${{ inputs.scaleway-cluster-id }}
          rollout-deployments: ${{ inputs.cluster-deployments }}
          rollout-labels: ${{ inputs.cluster-labels }}
          rollout-namespace: ${{ needs.fetch-namespace.outputs.value }}
          scaleway-organization-id: ${{ inputs.scaleway-organization-id }}
          scaleway-project-id: ${{ inputs.scaleway-project-id }}
          scaleway-region: ${{ inputs.scaleway-region }}
          scaleway-access-key: ${{ secrets.SCALEWAY_ACCESS_KEY }}
          scaleway-secret-key: ${{ secrets.SCALEWAY_SECRET_KEY }}
