---
name: Build & deploy to environment (DigitalOcean)

#
# Build the docker image, and deploy it to the given environment.
#

on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      environment:
        description: Target environment to deploy to
        type: string
        required: true
      # DigitalOcean information
      digitalocean-container-registry:
        description: Container registry endpoint
        required: true
        type: string
      digitalocean-cluster-id:
        description: Target cluster ID
        required: true
        type: string
      # Cluster info
      cluster-deployments:
        description: List of deployments to rollout
        required: true
        type: string
    secrets:
      DIGITALOCEAN_API_USER:
        description: DigitalOcean user email
        required: true
      DIGITALOCEAN_API_TOKEN:
        description: DigitalOcean API token
        required: true

jobs:
  fetch-namespace:
    uses: ./.github/workflows/github-fetch-environment-variable.yml
    with:
      environment: ${{ inputs.environment }}
      variable: K8S_NAMESPACE

  build-and-push:
    uses: ./.github/workflows/docker-build-and-push.yml
    with:
      container-registry: ${{ inputs.digitalocean-container-registry }}
      tag: ${{ inputs.environment }}
    secrets:
      CONTAINER_REGISTRY_USERNAME: ${{ secrets.DIGITALOCEAN_API_USER }}
      CONTAINER_REGISTRY_PASSWORD: ${{ secrets.DIGITALOCEAN_API_TOKEN }}

  rollout:
    needs: [fetch-namespace, build-and-push]
    uses: ./.github/workflows/docker-rollout-digitalocean.yml
    with:
      cluster-name: ${{ inputs.digitalocean-cluster-id }}
      cluster-deployments: ${{ inputs.cluster-deployments }}
      cluster-namespace: ${{ needs.fetch-namespace.outputs.value }}
    secrets: inherit
