---
name: Promote to environment (DigitalOcean)

#
# Calculate previous environment, re-tag the image and roll it out.
#

on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      environment-source:
        description: Source environment to deploy FROM (defaults to previous environment)
        type: string
        required: false
      environment-target:
        description: Target environment to deploy TO
        type: string
        required: true
      # DigitalOcean information
      digitalocean-container-registry:
        description: Container registry endpoint
        required: true
        type: string
      digitalocean-cluster-id:
        description: Target cluster ID
        required: true
        type: string
      # Cluster info
      cluster-deployments:
        description: List of deployments to rollout
        required: false
        type: string
      cluster-labels:
        description: List of labels to rollout
        required: false
        type: string
      # Extra options, probably not needed
      environment-map:
        description: Environment map (JSON, fallback to default map)
        type: string
        required: false
    secrets:
      DIGITALOCEAN_API_USER:
        description: DigitalOcean user email
        required: true
      DIGITALOCEAN_API_TOKEN:
        description: DigitalOcean API token
        required: true

jobs:
  promote-tag:
    name: Promote to ${{ inputs.environment-target }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment-target }}
    steps:
      - name: Re-tag image
        uses: wisemen-digital/devops-ga-docker-promote-tag@main
        with:
          container-registry: ${{ inputs.scaleway-container-registry }}
          container-registry-username: ${{ secrets.DIGITALOCEAN_API_USER }}
          container-registry-password: ${{ secrets.DIGITALOCEAN_API_TOKEN }}
          source-tag: ${{ inputs.environment-source }}
          target-tag: ${{ inputs.environment-target }}
          tag-map: ${{ inputs.environment-map }}
      - name: Rollout on cluster
        uses: wisemen-digital/devops-ga-k8s-rollout@main
        with:
          vendor: digitalocean
          cluster-id: ${{ inputs.digitalocean-cluster-id }}
          rollout-deployments: ${{ inputs.cluster-deployments }}
          rollout-labels: ${{ inputs.cluster-labels }}
          rollout-namespace: ${{ needs.fetch-namespace.outputs.value }}
          digitalocean-api-token: ${{ secrets.DIGITALOCEAN_API_TOKEN }}
